function plan = buildfile
%BUILDFILE Define AIM continuous-integration tasks.

    import matlab.buildtool.tasks.CodeIssuesTask
    import matlab.buildtool.tasks.TestTask

    repoRoot = fileparts(mfilename("fullpath"));
    addpath(fullfile(repoRoot, "src"));

    plan = buildplan;

    plan("check") = CodeIssuesTask(["src" "tests" "buildfile.m"], ...
        Configuration="factory", ...
        ErrorThreshold=0, ...
        WarningThreshold=Inf, ...
        Results=["artifacts/code-issues.sarif" "artifacts/code-issues.mat"], ...
        Description="Run MATLAB Code Analyzer; errors fail and warnings are reported.");

    coveredSources = [
        "src/WENO.m"
        "src/Isotherm_functions.m"
        "src/IAST_func_NR.m"
    ];

    plan("test") = TestTask("tests", ...
        SourceFiles=coveredSources, ...
        Strict=true, ...
        OutputDetail="detailed", ...
        TestResults=["artifacts/test-results.xml" "artifacts/test-results.mat"], ...
        CodeCoverageResults=["artifacts/coverage.xml" "artifacts/coverage.mat"], ...
        Description="Run AIM unit and numerical-invariant tests.");
end
