function format_string = get_intro_string(app_name)
    doc_link = "https://mtap-research.github.io/AIM/";
    repo_link = "https://github.com/Chung-Research-Group/AIM.git";
    format_string = sprintf('%s\n', repmat('*', 1, 74))...
            + sprintf("Welcome to AIM %s. ", app_name)...
            + sprintf("Please visit \n%s\n for detailed documentation.\n", doc_link)...
            + sprintf("Please visit \n%s\n for latest updates.\n", repo_link)...
            + sprintf('%s\n', repmat('*', 1, 74));
end