function format_string = get_intro_string(app_name)
    doc_link = "https://mtap-research.github.io/AIM/";
    format_string = sprintf('%s\n', repmat('*', 1, 74))...
            + sprintf("Welcome to AIM %s. ", app_name)...
            + sprintf("Please visit \n%s\n for detailed documentation.\n", doc_link)...
            + sprintf('%s\n', repmat('*', 1, 74));
end